import { BaseEntity } from 'app/core';
import { IRnsQuotationVariant } from 'app/entities/rns-quotation-variant';

export class AuctionVrnt implements BaseEntity {
    constructor(
        public id?: number,
        public title?: string,
        public applicable?: boolean,
        public textOne?: string,
        public uomOne?: string,
        public convFactOne?: number,
        public qtyOne?: number,
        public priceOne?: number,
        public amountOne?: number,
        public textTwo?: string,
        public uomTwo?: string,
        public convFactTwo?: number,
        public qtyTwo?: number,
        public priceTwo?: number,
        public amountTwo?: number,
        public textThree?: string,
        public uomThree?: string,
        public convFactThree?: number,
        public qtyThree?: number,
        public priceThree?: number,
        public amountThree?: number,
        public textFour?: string,
        public uomFour?: string,
        public convFactFour?: number,
        public qtyFour?: number,
        public priceFour?: number,
        public amountFour?: number,
        public textFive?: string,
        public uomFive?: string,
        public convFactFive?: number,
        public qtyFive?: number,
        public priceFive?: number,
        public amountFive?: number,
        public textSix?: string,
        public uomSix?: string,
        public convFactSix?: number,
        public qtySix?: number,
        public priceSix?: number,
        public amountSix?: number,
        public textSeven?: string,
        public uomSeven?: string,
        public convFactSeven?: number,
        public qtySeven?: number,
        public priceSeven?: number,
        public amountSeven?: number,
        public textEight?: string,
        public uomEight?: string,
        public convFactEight?: number,
        public qtyEight?: number,
        public priceEight?: number,
        public amountEight?: number,
        public textNine?: string,
        public uomNine?: string,
        public convFactNine?: number,
        public qtyNine?: number,
        public priceNine?: number,
        public amountNine?: number,
        public textTen?: string,
        public uomTen?: string,
        public convFactTen?: number,
        public qtyTen?: number,
        public priceTen?: number,
        public amountTen?: number,
        public variant?: IRnsQuotationVariant,
        public overTime?: number
    ) {
        this.applicable = false;
    }
}
