/* after changing this file run 'npm run webpack:build' */
/* tslint:disable */
import '../content/scss/vendor.scss';

// Imports all fontawesome core and solid icons

import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faUser,
    faSort,
    faSortUp,
    faSortDown,
    faSync,
    faEye,
    faBan,
    faTimes,
    faArrowLeft,
    faSave,
    faPlus,
    faMinus,
    faPencilAlt,
    faBars,
    faThList,
    faUserPlus,
    faRoad,
    faTachometerAlt,
    faHeart,
    faList,
    faBell,
    faBook,
    faHdd,
    faFlag,
    faWrench,
    faClock,
    faCloud,
    faSignOutAlt,
    faSignInAlt,
    faCalendarAlt,
    faSearch,
    faTrashAlt,
    faAsterisk,
    faTasks,
    faHome,
    faArrowRight,
    faCog,
    faChevronUp,
    faChevronDown,
    faQuoteRight,
    faGavel,
    faDatabase,
    faUserCircle,
    faCalendar,
    faEdit,
    faCheck,
    faFilePdf,
    faEnvelope,
    faCopy,
    faExchangeAlt,
    faRupeeSign,
    faPaperclip,
    faStar,
    faPlay,
    faPause,
    faRetweet,
    faBezierCurve,
    faCommentAlt,
    faCircle,
    faInbox,
    faChartLine,
    faWonSign,
    faDownload,
    faPlusCircle,
    faMinusCircle,
    faComments,
    faFileExcel,
    faTags,
    faChartBar,
    faFileDownload,
    faFileUpload
} from '@fortawesome/free-solid-svg-icons';

import { faWikipediaW, faElementor } from '@fortawesome/free-brands-svg-icons';

// Adds the SVG icon to the library so you can use it in your page
library.add(faUser);
library.add(faSort);
library.add(faSortUp);
library.add(faSortDown);
library.add(faSync);
library.add(faEye);
library.add(faBan);
library.add(faTimes);
library.add(faArrowLeft);
library.add(faSave);
library.add(faPlus);
library.add(faMinus);
library.add(faPencilAlt);
library.add(faBars);
library.add(faHome);
library.add(faThList);
library.add(faUserPlus);
library.add(faRoad);
library.add(faTachometerAlt);
library.add(faHeart);
library.add(faList);
library.add(faBell);
library.add(faTasks);
library.add(faBook);
library.add(faHdd);
library.add(faFlag);
library.add(faWrench);
library.add(faClock);
library.add(faCloud);
library.add(faSignOutAlt);
library.add(faSignInAlt);
library.add(faCalendarAlt);
library.add(faSearch);
library.add(faTrashAlt);
library.add(faAsterisk);
library.add(faArrowRight);
library.add(faCog);
library.add(faChevronUp);
library.add(faChevronDown);
library.add(faGavel);
library.add(faQuoteRight);
library.add(faDatabase);
library.add(faUserCircle);
library.add(faCalendar);
library.add(faEdit);
library.add(faCheck);
library.add(faFilePdf);
library.add(faEnvelope);
library.add(faWikipediaW);
library.add(faElementor);
library.add(faCopy);
library.add(faExchangeAlt);
library.add(faRupeeSign);
library.add(faPaperclip);
library.add(faStar);
library.add(faPlay);
library.add(faPause);
library.add(faRetweet);
library.add(faBezierCurve);
library.add(faCommentAlt);
library.add(faCircle);
library.add(faInbox);
library.add(faChartLine);
library.add(faWonSign);
library.add(faDownload);
library.add(faPlusCircle);
library.add(faMinusCircle);
library.add(faComments);
library.add(faFileExcel);
library.add(faTags);
library.add(faChartBar);
library.add(faFileDownload);
library.add(faFileUpload);
// jhipster-needle-add-element-to-vendor - JHipster will add new menu items here
