import { BaseEntity, BaseEntityQuotationVariants, IUser } from 'app/core';
import { RnsTypeMaster } from '../rns-type-master';
import { AuctionPauseDetails } from '../auction-pause-details';
import { IRnsCatgMaster } from 'app/entities/rns-catg-master';

export class RnsQuotation implements BaseEntity {
    constructor(
        public id?: number,
        public catgName?: string,
        public quoteNumber?: string,
        public quoteType?: string,
        public rnsTypeMaster?: RnsTypeMaster,
        public validity?: any,
        public auctionValidity?: any,
        public validityExpired?: any,
        public internalRemarks?: string,
        public createdOn?: any,
        public crmRequestNumber?: string,
        public requestedBy?: string,
        public pchCode?: string,
        public targetPcd?: any,
        public buyerCode?: string,
        public buyerName?: string,
        public merchantRemarks?: string,
        public date?: any,
        public articleCode?: string,
        public articleDesc?: string,
        public variants?: BaseEntityQuotationVariants[],
        public quotationVendors?: BaseEntity[],
        public rnsCatgCode?: IRnsCatgMaster,
        public published?: boolean,
        public template?: string,
        public workflowStatus?: string,
        public rfq?: boolean,
        public auction?: boolean,
        public workflow?: boolean,
        public auctionDetails?: any,
        public projectTitle?: string,
        public displayVariant?: string,
        public eventType?: string,
        public createdBy?: string,
        public user?: IUser,
        public noOfLot?: number,
        public sourceTeam?: string,
        public rfqPublishDate?: any,
        public auctionPublishDate?: any,
        public rfqStatus?: string,
        public paused?: boolean,
        public auctionPauseDetails?: AuctionPauseDetails,
        public auctionClose?: boolean,
        public errorMessage?: string,
        public approvedFlag?: string,
        public approvedBy?: string,
        public approvedDate?: any,
        public rfqApplicable?: boolean,
        public auctionApplicable?: boolean,
        public rfqActive?: boolean,
        public rfqMessage?: string,
        public rfbActive?: boolean,
        public rfbMessage?: string,
        public rfbStatus?: string,
        public workflowActive?: boolean,
        public workflowMessage?: string,
        public rfqIcon?: string,
        public rfbIcon?: string,
        public workflowIcon?: string,
        public updatedBy?: string,
        public updatedDate?: any,
        public closedBy?: string,
        public closedDate?: any
    ) {}
}
